--#### CHAPTER 1 QUERY PRIMER---------
--CREATING DATABASE
CREATE DATABASE LEARNING_SQL;

--QUERY PRIMER--
SELECT CURRENT_DATE; --> yyyy_mm_dd

--* IS A SHORT HAND TO RETURN EVERY COLOUMN, FROM IS USED TO SPECIFY TABLE/S TO RETRIEVE DATA.
SELECT * FROM DF_CHC_MARKET_DEV.STG_EG.STG_EG_SALES_NATIONAL_MTH;

--QUERY CLAUSES: There are 8 different clauses that can be add-up in a query.
--select: speciies the coloumn to be included in the result set.
--from: identifies the table from which data should be pulled.
--where: remove unwanted rows in the result (a type of filter).
--group by: group rows together by common values.
--having: remove unwanted rows in the result set based on grouping.
--qualify: remove unwanted rows in the result set base in result of windoing function.
--order by: sorts the result by one or more coloumn.
--limit: restrics numbers of rows in result set.

--SELECT CLAUSE
--CAN CONTAIN LITRALS (STRING,NUMBER), EXPRESSION, BUILTIN FUNCTION/USER DEFINE FUNCTION
SELECT 'WELCOME TO SNOWFLAKE BY SHUBHAM (THE "SUPER-STAR😎")'; -- SIMPLE MSG 
SELECT 2*8; -- EXPRESSION
SELECT CURRENT_DATE; -- BUILTIN FUNCTION
SELECT * FROM DF_CHC_MARKET_DEV.STG_EG.STG_EG_SALES_NATIONAL_MTH; -- FULL TABLE
SELECT CORPORATION,MANUFACTURER,PRODUCT FROM STG_EG.STG_EG_SALES_NATIONAL_MTH; --SPECIFIC COLOUMNS PULLING

---COLOUMN ALIASES: TO SPECIFY YOUR OWN NAME FOR ANY COLOUMN. it is preceeded by AS keyword.
SELECT 'WELCOME TO SNOWFLAKE BY SHUBHAM (THE "SUPER-STAR😎")' AS MSG,
2*8 AS EXPN, DAYNAME(CURRENT_DATE) AS DAY_NAME,
CURRENT_DATE || ' ' || DAYNAME(CURRENT_DATE) || 'day' AS FULL_DATE;

--REMOVING DUPLICATES: USE DISTINCT TO IDENTIFY UNIQUE ITEMS.
SELECT DISTINCT(CHANNEL) FROM DF_CHC_MARKET_DEV.STG_EG.STG_EG_SALES_NATIONAL_MTH;

--MAKE A QUERY TO IDENTIFY THE DUPLICATES FOR A COLOUMN
SELECT COUNT(CHANNEL), CHANNEL,
CASE WHEN COUNT(CHANNEL) > 1 THEN 'DUPLICATES OCCURENCE' ELSE 'UNIQUE' END AS RESULT_X
FROM DF_CHC_MARKET_DEV.STG_EG.STG_EG_SALES_NATIONAL_MTH
GROUP BY CHANNEL;

--MAKE A QUERY TO READ DUPLICATES FORM A COLOUMN
SELECT CHANNEL
FROM DF_CHC_MARKET_DEV.STG_EG.STG_EG_SALES_NATIONAL_MTH
GROUP BY CHANNEL
HAVING (COUNT(CHANNEL) > 1 );

--THE FROM CLAUSE: RETRIVING DATA FROM A SINGLE OR MULTIPLE TABLES

SELECT DISTINCT(CHANNEL) FROM DF_CHC_MARKET_DEV.STG_EG.STG_EG_SALES_NATIONAL_MTH; --SINGLE TABLE

SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND
S.CORPORATION = P.CORPORATION AND
S.ATC4 = P.ATC4;

--GENERATING DATA SETS USING VALUES: GENERATE DATA ON THE FLY USING VALUE SUBCLAUSE.
SELECT * FROM
(VALUES
('JAN',1,'YEAR_FIRST_MONTH'),('FEB',2,'LEAP_YEAR'),('MAR',3,'QRT-1 END'),('APR',4,''),('MAY',5,''),('JUN',6,'QRT-2 END'),('JUL',7,''),('AUG',8,''),('SEP',9,'QRT-3 END'),('OCT',10,''),('NOV',11,''),('DEC',12,'YEAR_LAST_MONTH'))
AS MONTHS (MONTH_NAME, MONTH_NUM, COMMENT_X);

--THE WHERE CLAUSE: IT IS USED TO RETRIEVE SUBSETS OF THE ROWS BASED ON EXPRESSION, it is used to filter the data.
SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND
S.CORPORATION = P.CORPORATION AND
S.ATC4 = P.ATC4
WHERE S.CHANNEL = 'RETAIL';

SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND
S.CORPORATION = P.CORPORATION AND
S.ATC4 = P.ATC4
WHERE S.CHANNEL LIKE '%RETAIL';


SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND
S.CORPORATION = P.CORPORATION AND
S.ATC4 = P.ATC4
WHERE S.CHANNEL ILIKE  'retail';

--THE GROUP BY CLAUSE: USED FOR GROUPPING ROWS, USEFUL FOR REPORTING AND DATA ANALYSIS. 
--EVELUATION:WHERE->GROUP BY -> HAVING

SELECT COUNTRY_ID,COUNT(COUNTRY_ID)  FROM
DF_CHC_MARKET_DEV.DWH_MARKET_SALES.FCT_SALES_NATIONAL_MTH
GROUP BY COUNTRY_ID;

--THE HAVING CLAUSE: CONCEPT OF FILTERING
SELECT COUNTRY_ID,COUNT(COUNTRY_ID)  FROM
DF_CHC_MARKET_DEV.DWH_MARKET_SALES.FCT_SALES_NATIONAL_MTH
WHERE CALENDAR_ID LIKE '2025%'  -- 1 RESOLVE
GROUP BY COUNTRY_ID  --2 RESOLVING
HAVING (COUNT(COUNTRY_ID) >= 5000); --3 RESOLVING

--THE QUALIFY CLAUSE: THIS IS 3RD CLAUSE FOR FILTERING AFTER WHERE & HAVING, BUT IT IS A SPECIAL-PURPOSE CLAUSE USED ONLY FOR FILTERING ROW BASED ON RESULT OF WINDOWING FUNCTIONS (RANK()).
-- FOR NORMAL ROW FILTER USE WHERE CLAUSE, FOR FILTERING ON BASIS OF GROUP BY CLAUSE USE HAVING SUBCLAUSE AND FOR FILTERING USING ANY WINDOW FUNCTION USE QUALIFY SUBCLAUSE.

SELECT NAME,
RANK() OVER (ORDER BY LENGTH(D.NAME) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
QUALIFY RNK_X >= 10;

SELECT NAME
FROM (SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D) X
QUALIFY RNK_X >= 1;

--THE ORDER BY CLAUSE: USE TO SORT THE RESULT ON BASIS OF ALPHABETICALLY, NUMERICALLY OR CHRONOLOGICALLY, USE AT END OF QUERY BY PROVIDING COLOUMN NAME OR COLOUMN POSITION.

SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
QUALIFY RNK_X >= 1
ORDER BY COUNTRY_ID;

SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
QUALIFY RNK_X >= 1
ORDER BY 3 DESC; -- ORDERING BY RNK_X

--THE LIMIT: ALLOWS YOU TO SPECIFY HOW MANY ROWS TO RETURN, STARTING FROM FIRST OR LAST.
SELECT TOP 10 * FROM DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY;

SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
QUALIFY RNK_X >= 1
ORDER BY 3 DESC
LIMIT 10; -- FIRST 10 ROWS IN OUTPUT

SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
QUALIFY RNK_X >= 1
ORDER BY 3 DESC
LIMIT 10 OFFSET 240; -- LAST 10 ROWS / ROWS AFTER 240

SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
QUALIFY RNK_X >= 1
ORDER BY 3 DESC
LIMIT 10;

--###CHAPTER-2 FILTERING ####
--CONDITON EVALUATION: WHERE CLAUSE is uesd, we can add one or more condition using 'AND' / 'OR'; it returns result when condition is TRUE, for more precise conditioning use parenthesis '()'.

SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
where (country_id = 'NG' or country_id = 'MK') and name is not null -- 'and' is a must sastifactory condition, and for 'or' any one is fine.
QUALIFY RNK_X >= 1 -- TYPE OF FILTER BUT EXCLESUIVE FOR WINDOW FUNCTION.
ORDER BY 3 DESC
LIMIT 10;

--USING NOT OPERATOR: IN RETRIVING ROWS FOR EVERYONE EXCEPT THOSE FOUND
SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
where NOT (country_id = 'NG' or country_id = 'MK') and name is not null -- 'and' is a must sastifactory condition, and for 'or' any one is fine, BUT FETECHING ALL ROWS EXCEPT 'NG'&'MK'
QUALIFY RNK_X >= 1 -- TYPE OF FILTER BUT EXCLESUIVE FOR WINDOW FUNCTION.
ORDER BY 3 DESC
LIMIT 10;

SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
where (country_id <> 'NG' OR country_id <> 'MK') and name is not null  -- 'and' is a must sastifactory condition, and for 'or' any one is fine. BUT FETECHING ALL ROWS EXCEPT 'NG'&'MK'. NOTE: '<>' IS SHORT HAND FOR 'NOT'.
QUALIFY RNK_X >= 1 -- TYPE OF FILTER BUT EXCLESUIVE FOR WINDOW FUNCTION.
ORDER BY 3 DESC
LIMIT 10;