----#### CHAPTER 2 FILTERING---------

--CONDITION COMPONENTS: A CONDITON IS MADE UP OF ONE ORE MORE EXPRESSION COMBINED WITH ONE OR MORE OPERATORS. IT CAN CONTAIN COLOUMN OF A TABLE,NUMBER,DATE,STRING LITERLAS,BUILTIN FUNCTIONS, SUBQUERY AND LIST OF EXPRESSION. OPERATOR USED WITHIN CONDITION INCLUDES (COMPARISON OPERATOR =,<,>,!=,<>) AND (ARITHMETIS OPERATOR +,-,*,/).
--EQUALITY CONDITION: NAME = 'ABC'/ORDER_DATE = '02/09/2025' --> THERE ARE KNOWN AS EQUALITY CONDITION,CAUSE THEY EQUATE ONE EXPRESSION TO ANOTHER. MOSTLY USE FOR JOINING/FILTERING.
SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND -- EQUALITY CONDITION
S.CORPORATION = P.CORPORATION AND -- EQUALITY CONDITION
S.ATC4 = P.ATC4 -- EQUALITY CONDITION
WHERE S.CHANNEL LIKE '%RETAIL'; -- FILTER

--INEQUALITY CONDITION: COMMON TYPE OF CONDITION WHICH EVALUATES AS TRUE WHEN TWO EXPRESSION ARE NOT SAME.
SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND -- EQUALITY CONDITION
S.CORPORATION = P.CORPORATION AND -- EQUALITY CONDITION
S.ATC4 = P.ATC4 -- EQUALITY CONDITION
WHERE (S.CHANNEL <> '%RETAIL' OR UPPER(S.CHANNEL != 'HOSPITAL'); --INEQUALITY CONDITION

--RANGE CONDITION: DETERMINE IF AN EXPRESSION FALLS WITHIN A SPECIFIED RANGE. COMMONLY USED WITH NUMERIC,DATE AND STRINGS. UTILIZE THE BETWEEN OPERATOR.
SELECT * FROM DWH_MARKET_SALES.FCT_SALES_NATIONAL_MTH F WHERE F.COUNTRY_ID BETWEEN 9 AND 12 ; -- 9 AND 12 ARE ALSO INCLUDED IN RESULT
SELECT * FROM DWH_MARKET_SALES.FCT_SALES_NATIONAL_MTH F WHERE F.INSERTED_TS BETWEEN TO_DATE('2025-10-28', 'YYYY-MM-DD') AND TO_DATE('2025-10-30', 'YYYY-MM-DD');
SELECT * FROM DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY WHERE COUNTRY_ID BETWEEN 'IN' AND 'IX';

--MEMBERSHIP CONDITION: BINDING MULTIPLE CONDION IN A SINGLE STATEMENT IS MEMBERSHIP CONDITION. IT USES 'IN' OPERATOR ALSO 'NOT' CAN BE INCLUDED IF REQUIRED.
SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND -- EQUALITY CONDITION
S.CORPORATION = P.CORPORATION AND -- EQUALITY CONDITION
S.ATC4 = P.ATC4 -- EQUALITY CONDITION
WHERE S.CHANNEL IN ('RETAIL' , 'HOSPITAL'); --MEMBERSHIP CONDITION


SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND -- EQUALITY CONDITION
S.CORPORATION = P.CORPORATION AND -- EQUALITY CONDITION
S.ATC4 = P.ATC4 -- EQUALITY CONDITION
WHERE S.CHANNEL NOT IN ('RETAIL' , 'HOSPITAL'); --MEMBERSHIP CONDITION USING NOT

--MATCHING CONDITION: TRYING TO SEARCH ANY ROW USING ANY COLOUMS PARTIAL STRING MATCH, LIKE BEGIN/END WITH CERTAIN SUBSTRING/CHARACTER USING WILDCARD. '%' --> ANY NUMBER IF CHARACTER AND '_' EXACTLY ONE CHARACTER. ALSO, REGEXP_LIKE CAN BE USED.
SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND -- EQUALITY CONDITION
S.CORPORATION = P.CORPORATION AND -- EQUALITY CONDITION
S.ATC4 = P.ATC4 -- EQUALITY CONDITION
WHERE S.CHANNEL LIKE '%RETAIL'; --WILDCARD SEARCH

SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
where country_id LIKE 'N_' OR --WILDCARD SEARCH
country_id LIKE '%K' --WILDCARD SEARCH
and name is not null 
QUALIFY RNK_X >= 1 -- TYPE OF FILTER BUT EXCLESUIVE FOR WINDOW FUNCTION.
ORDER BY 3 DESC
LIMIT 10;

SELECT NAME,COUNTRY_ID,
RANK() OVER (ORDER BY LENGTH(D.COUNTRY_ID) ASC) AS RNK_X FROM
DF_CHC_MARKET_DEV.TECH_TMP.DIM_COUNTRY D
where REGEXP_LIKE(D.COUNTRY_ID, '^[MU].*') -- STARTS WITH M OR U AND CAN HAVE ANY NUMBER OF CHARACTER IN COUNTRY_ID COLOUMN.
and name is not null 
QUALIFY RNK_X >= 1 -- TYPE OF FILTER BUT EXCLESUIVE FOR WINDOW FUNCTION.
ORDER BY 3 DESC
LIMIT 10;

--NULL VALUES: AN EXPRESSION CAN BE NULL, BUT IT CAN NEVER EQUAL NULL. TWO NULLS ARE NEVER EQUAL TO EACH OTHER.
SELECT 'YES' AS IS_VALID WHERE NULL = NULL; --USES FILTER CONDITION NULL = NULL; ALWAYS EVELUATE AS FALSE
SELECT 'YES' AS IS_VALID WHERE NULL IS NULL; --USES 'IS' NULL OPERATOR, WHICH IN THIS CASE EVALUATES AS TRUE.

--CREATING A TABLE WITH VALUES AND DELETE TABLE.
--IT IS EASIER THAN CREATING AN EMPTY TABLE AND THEN EXECUTING MULTIPLE INSERT STATEMENTS TO POPULATE THE TABLE...
CREATE TABLE STG_EG.NULL_EXAMPLE (NUM_COL NUMBER, CHAR_COL VARCHAR(10))
AS SELECT * FROM (VALUES     --VALUE SUBCLAUSE IS USEFUL WHEN YOU NEED TO GENERATE A SMALL DATA SET, EITHER BY ITSELF OR TO JOIN TO OTHER TABLES.
(1,'ABC'),(2,'JKL'),(NULL,'QRS'),(3,'NULL')
);

SELECT * FROM STG_EG.NULL_EXAMPLE;

--DELETE A TABLE
DROP TABLE STG_EG.NULL_EXAMPLE;

SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES,LC_60,LC_58 FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND -- EQUALITY CONDITION
S.CORPORATION = P.CORPORATION AND -- EQUALITY CONDITION
S.ATC4 = P.ATC4 -- EQUALITY CONDITION
WHERE S.CHANNEL LIKE '%RETAIL' --WILDCARD SEARCH
AND S.LC_60 IS NULL; 

SELECT * FROM STG_EG.STG_EG_SALES_NATIONAL_MTH;

SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES,LC_60,LC_58 FROM 
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND -- EQUALITY CONDITION
S.CORPORATION = P.CORPORATION AND -- EQUALITY CONDITION
S.ATC4 = P.ATC4 -- EQUALITY CONDITION
WHERE S.CHANNEL LIKE '%RETAIL' --WILDCARD SEARCH
AND S.ATC4 <> 'ATC4'
AND NVL(LC_60,0) --NVL FUNCTION WILL SUBSTITUE THE VALUE 0 FOR ANY NULL VALUES
ORDER BY LC_60; 

SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES,LC_60,NVL(LC_58,0) FROM --NVL FUNCTION WILL SUBSTITUE THE VALUE 0 FOR ANY NULL VALUES
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING MULTIPLE TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND -- EQUALITY CONDITION
S.CORPORATION = P.CORPORATION AND -- EQUALITY CONDITION
S.ATC4 = P.ATC4 -- EQUALITY CONDITION
WHERE S.CHANNEL LIKE '%RETAIL' --WILDCARD SEARCH
AND S.ATC4 <> 'ATC4'
AND NVL(LC_60,0) --NVL FUNCTION WILL SUBSTITUE THE VALUE 0 FOR ANY NULL VALUES
ORDER BY LC_60;

-- FILTERING USING SNOWSIGHT

SELECT DISTINCT(PROCESS_ID), COUNTRY,CORPORATION,PRODUCT,PACK,INSERTED_TS FROM PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP
WHERE INSERTED_TS BETWEEN TO_DATE('2025-10-09','YYYY-MM-DD') AND TO_DATE('2025-10-12','YYYY-MM-DD')
GROUP BY ALL;


SELECT DISTINCT(PROCESS_ID), COUNTRY,CORPORATION,PRODUCT,PACK,INSERTED_TS FROM PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP
WHERE INSERTED_TS = :daterange -- VALUE FOR :daterange IS PROVIDED BY SNOWSIGHT QUERY FILTER TAB. --TO SEE HOW THE QUERY IS EVALUATED, GOTO MONITOR>QUERY HISTORY
GROUP BY ALL;
--YOU CAN ADD YOUR CUSTOM FILTER USING MANAGE FILTER. IN TOP LEFT OF SNOWSIGHT CONSOLE.