--#### CHAPTER 3 JOINS---------
--JOINS: TO BRING TOGETHER DATA OF MULTIPLE TABLES IN ORDER TO RETRIEVE DATA IS KNOWS AS JOINING OF TABLES.
--IT USES UNIQUE IDENTIFIER TO JOIN TABLES.
--THE from CLAUSE LISTS THE TABLES TO BE JOINED AND THE on SUBCLAUSE CONTAINS THE JOIN CONDITION/S NEEDED TO TRANSVERSE FROM ONE TO ANOTHER TABLE.
SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES,LC_60,NVL(LC_58,0) FROM --NVL FUNCTION WILL SUBSTITUE THE VALUE 0 FOR ANY NULL VALUES.
STG_EG.STG_EG_SALES_NATIONAL_MTH S
JOIN  -- JOINING 2 TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P
ON S.CHANNEL = P.CHANNEL AND -- EQUALITY CONDITION
S.CORPORATION = P.CORPORATION AND -- EQUALITY CONDITION
S.ATC4 = P.ATC4 -- EQUALITY CONDITION
WHERE S.CHANNEL LIKE '%RETAIL' --WILDCARD SEARCH
AND S.ATC4 <> 'ATC4'
AND NVL(LC_60,0) --NVL FUNCTION WILL SUBSTITUE THE VALUE 0 FOR ANY NULL VALUES
ORDER BY LC_60
LIMIT 100;

--TABLE ALIASES: YOU CAN PROVIDE ALIASES FOR THE TABLES IN THE from CLAUSE; USEFUL FOR ENHANCING READILIBITY OF QUERY.
-- TABLE ALIASE ARE ALSO PROVIDED IN select CLAUSE & IN on SUBCLAUSE.
SELECT S.CHANNEL,S.MANUFACTURER,P.MOLECULES,LC_60,NVL(LC_58,0) FROM --NVL FUNCTION WILL SUBSTITUE THE VALUE 0 FOR ANY NULL VALUES.
STG_EG.STG_EG_SALES_NATIONAL_MTH S --> S IS A PET NAME/ ALIASE FOR STG_EG.STG_EG_SALES_NATIONAL_MTH
JOIN  -- JOINING 2 TABLES
PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP P  --> P IS A PET NAME/ ALIASE FOR PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP.
ON S.CHANNEL = P.CHANNEL AND -- EQUALITY CONDITION
S.CORPORATION = P.CORPORATION AND -- EQUALITY CONDITION
S.ATC4 = P.ATC4 -- EQUALITY CONDITION
WHERE S.CHANNEL LIKE '%RETAIL' --WILDCARD SEARCH
AND S.ATC4 <> 'ATC4'
AND NVL(LC_60,0) --NVL FUNCTION WILL SUBSTITUE THE VALUE 0 FOR ANY NULL VALUES
ORDER BY LC_60
LIMIT 100;

--INNER JOINS: IT IS MOST COMMONLY USED TYPE OF JOIN, ALSO ARE THE TYPE IF DEFAULT JOINS, CAUSE NO NEED TO SPECIFY THE inner KEYWORD IN from CLAUSE.
-- RESULT SET INCLUDES ONLY THOSE ROWS FOR WHICH THERE IS A VALID JOIN BETWEEN TWO TABLES.
--ONLY MATCHING ROWS FROM BOTH THE TABLE.

CREATE TABLE STG_EG.customer_simple_PRACTICE (custkey, custname) AS SELECT * FROM
(VALUES (101,'BOB'),(102,'KIM'),(103,'JIM'));

CREATE OR REPLACE TABLE STG_EG.order_simple_PRACTICE (ordernum, custname) AS SELECT * FROM
(VALUES (990,101),(991,102),(992,101),(993,104));

SELECT O.ORDERNUM, O.CUSTNAME, C.CUSTNAME FROM STG_EG.order_simple_PRACTICE AS O INNER JOIN STG_EG.customer_simple_PRACTICE AS C ON O.CUSTNAME = C.CUSTKEY;

--LEFT OUTER JOINS: COMMON TYPE OF JOIN, RETURNS ALL OF THE ROWS FROM TABLE A REGARDLESS OF WHETHER A JOIN EXISTS TO TABLE B. JOIN WAS SPECIFIED TO BE LEFT OUTER, MEANING THAT ALL ROWS FROM THE TABLE ON THE LEFT SIDE OF THE JOIN (ORDER_SIMPLE TABLE) SHOULD BE INCLUDED. ALL ELEMENTS FROM LEFT TABLE & MATCHING RECORDS FROM RIGHT TABLE.

SELECT O.ORDERNUM, O.CUSTNAME, C.CUSTNAME FROM STG_EG.order_simple_PRACTICE AS O LEFT OUTER JOIN STG_EG.customer_simple_PRACTICE AS C ON O.CUSTNAME = C.CUSTKEY;

--RIGHT OUTTER JOIN:RARELY USED JOIN, RETURNS ALL OF THE ROWS FROM TABLE B REGARDLESS OF WHETHER A JOIN EXISTS TO TABLE A. JOIN WAS SPECIFIED TO BE RIGHT OUTER, MEANING THAT ALL ROWS FROM THE TABLE ON THE RIGHT SIDE OF THE JOIN (CUSTOMER_SIMPLE TABLE) SHOULD BE INCLUDED.

SELECT O.ORDERNUM, O.CUSTNAME, C.CUSTNAME FROM STG_EG.order_simple_PRACTICE AS O RIGHT OUTER JOIN STG_EG.customer_simple_PRACTICE AS C ON O.CUSTNAME = C.CUSTKEY;

--CROSS JOINS: THE CROSS JOIN, WHICH IS A BIT OF A MISNOMER (THAT IS APPROPRIATE/WRONG) BECAUSE NO ACTUAL JOIN IS HAPPENING. RATHER THE TWO TABLES ARE MERGED TOGETHER, WHICH IS KNOWN AS CARTESIAN PRODUCT OF THE TWO TABLE. CROSS JOIN ON A TABLE WITH 50 ROWS TO ANOTHER WITH 150 ROWS, THE RESULT SET WOULD CONTAIN 7500 ROWS (50*150).
--ALSO CAN BE USE AS TO CONSTUCT DATA ON THE FLY.

--GENERATING TABLE USEING CROSS JOIN : GENERATE A QUARTERLY REPORT SPANNING THE YEAR 2020,2021 & 2022, BUT THERE ISN'T ANY TABLE IN DATABASE THAT CONTAINS INFORMATION ABOUT QUARTERS. GENERATE A ARESULT SET TO USE FOR YOUR QUERY TAHT INCLUDES THE 12 NEEDE ROWS (3 YEAR * 4 QUARTERS) BY BUILDING TWO DATA SETS AND MERGING THEM USING CROSS JOIN.
-- THE CROSS JOIN DOES NOT INCLUDE THE ON SUBCLAUSE, SINCE THERE IS NO JOIN BEING SPECIFIED. 

SELECT YEARS.YEARNUM, QTRS.QTRNAME, QTRS.STARTMONTH, QTRS.ENDMONTH
FROM
(VALUES (2020),(2021),(2022)) AS YEARS (YEARNUM) 
CROSS JOIN 
(VALUES ('Q1',1,3),('Q2',4,6),('Q3',7,9),('Q4',10,12))
AS QTRS (QTRNAME,STARTMONTH,ENDMONTH) ORDER BY 1,2;

--JOINING THREE OR MORE TABLES..
--EACH JOIN INCLUDES ITS OWN on SUBCLAUSE TO DEFINE THE APPROPRIATE JOIN CONDITION.THE SEQUENCE OF THE TABLES IN THE from CLAUSE MAKE NO DIFFERENCE.SNOWFLAKE SERVER WILL DETERMINE HOW BEST TO EXECUTE YOUR QUERIES AND WILL NOT ACCESS THE TABLE IN THE ORDER SPECIFIED IN YOUR from CLAUSE.

SELECT * FROM DF_CHC_MARKET_DEV.DWH_MARKET_SALES.FCT_SALES_NATIONAL_MTH F
WHERE SOURCE_PRODUCT_ID NOT in (
SELECT SOURCE_PRODUCT_ID FROM (
SELECT MD5(UPPER(TRIM(MST.COUNTRY)||IFNULL(NULLIF(TRIM(ATC4),''),'UNKNOWN')||IFNULL(NULLIF(TRIM(CORPORATION),''),'UNKNOWN')||IFNULL(NULLIF(TRIM(MANUFACTURER),''),'UNKNOWN')||IFNULL(NULLIF(TRIM(PRODUCT),''),'UNKNOWN')||IFNULL(NULLIF(TRIM(MOLECULE_LIST),''),'UNKNOWN')||IFNULL(NULLIF(TRIM(PACK),''),'UNKNOWN')||IFNULL(NULLIF(TRIM(NFC123),''),'UNKNOWN')||IFNULL(NULLIF(TRIM(PACK_LAUNCH_DATE),''),'UNKNOWN'))) AS SOURCE_PRODUCT_ID,
	DP.PANEL_ID,
	DC.COUNTRY_ID,
	MST.CALENDAR_ID,
	MST.UN,
	MST.LC,
	MST.SU,
	IFNULL(LC * DP.MANUFACTURER_RATE * IFNULL(RCR.EXCHANGE_RATE, 1), 0) AS VALUE_MNF_EU,
	IFNULL(LC * DP.TRADE_RATE * IFNULL(RCR.EXCHANGE_RATE, 1), 0) AS VALUE_TRADE_EU,
	IFNULL(LC * DP.PUBLIC_RATE * IFNULL(RCR.EXCHANGE_RATE, 1), 0) AS VALUE_PUBLIC_EU,
	CURRENT_TIMESTAMP AS INSERTED_TS
	FROM PSA_EG.PSA_EG_SALES_NATIONAL_MTH_TRANSP MST
	JOIN  DWH_MARKET_SALES.DIM_COUNTRY DC ON MST.COUNTRY=DC.COUNTRY
	JOIN DWH_MARKET_SALES.DIM_PANEL DP ON UPPER(DP.COUNTRY||DP.PANEL||DP.CHANNEL)=UPPER(TRIM(MST.COUNTRY)||TRIM(MST.PANEL)||TRIM(MST.CHANNEL)) 
	JOIN DWH_MARKET_SALES.FCT_CURRENCY_EXCHANGE_RATE RCR ON DP.CURRENCY_CD=RCR.CURRENCY_CD AND DC.COUNTRY_ID=RCR.COUNTRY_ID
	WHERE MST.LATEST_FLAG = 1 AND MST.CHANNEL = 'HOSPITAL') X )
AND F.COUNTRY_ID = 20;

--JOINING A TABLE TO ITSELF: BIT ODD JOINING, BUT VALID; SOME TABLE INCLUDE A self_referencing forign key, THAT IS INCLUDES A COLUMN THAT REFERENCE THE PRIMARY KEY WITHIN THE SAME TABLE. FOR SELF JOINING, USING SAME TABLE TWICE AND GIVING DIFFERENT ALICE. TABLE ALIASES ARE REQUIRED IN THIS QUERY BECAUSE YOU NEED TO REFFER TO EACH TABLE IN THE from CLAUSE USING A UNIQUE NAME. self-join IS NECESSARY NERE BECAUSE EACH ROE IN THE RESULT SET CONTAINS VALUES FROM TWO DIFFERENT ROWS IN THE employee TABLE.
CREATE TABLE STG_EG.SIMPLE_EMPLOYEE (EMPID NUMBER, EMP_NAME VARCHAR(30), MGR_EMPID NUMBER) AS SELECT * FROM 
(VALUES (1001,'BOB SMITH',NULL), (1002,'SUSAN JACKSON',1001),(1003,'GREG CARPENTER',1001),(1004,'ROBERT BUTLER',1002),(1005,'KIM JOSEPHS',1003),(1006,'JOHN TYLER',1004));

SELECT * FROM STG_EG.SIMPLE_EMPLOYEE;

SELECT E.EMPID, E.EMP_NAME, MGR.EMP_NAME AS MGR_NAME FROM STG_EG.SIMPLE_EMPLOYEE AS E 
INNER JOIN STG_EG.SIMPLE_EMPLOYEE AS MGR 
ON E.MGR_EMPID = MGR.EMPID; -- HERE YOU WILL NOT GET ROW SET FOR BOB SMITH. AS HE IS HIGEST. AS INNER JOIN IS USED..

SELECT E.EMPID, E.EMP_NAME, MGR.EMP_NAME AS MGR_NAME FROM STG_EG.SIMPLE_EMPLOYEE AS E 
LEFT OUTER JOIN STG_EG.SIMPLE_EMPLOYEE AS MGR -- HERE YOU WILL GET ROW SET FOR BOB SMITH. AS OUTTER JOIN IS USED..
ON E.MGR_EMPID = MGR.EMPID ORDER BY 1; 

--JOINING THE SAME TABLE TWICE..
-- TO ADD A COLOUMN IN A TABLE USE "alter","ADD", "COLOUMN".. 
ALTER TABLE STG_EG.SIMPLE_EMPLOYEE ADD COLUMN BIRTH_NATIONKEY INTEGER;
ALTER TABLE STG_EG.SIMPLE_EMPLOYEE ADD COLUMN IF NOT EXISTS CURRENT_NATIONKEY INTEGER;

--UPDATEING VALUE IN COLOUMN BASED ON ANY EQUATION/LOGIC.
UPDATE STG_EG.SIMPLE_EMPLOYEE 
SET BIRTH_NATIONKEY = EMPID - 1000,
CURRENT_NATIONKEY = EMPID - 999;

SELECT E.EMPID, E.EMP_NAME,
N1.COUNTRY AS BIRTH_NATION, N2.COUNTRY AS CURRENT_NATION FROM STG_EG.SIMPLE_EMPLOYEE E
INNER JOIN 
DF_CHC_MARKET_PROD.DWH_MARKET_SALES.DIM_COUNTRY AS N1 ON E.BIRTH_NATIONKEY = N1.COUNTRY_ID INNER JOIN 
DF_CHC_MARKET_PROD.DWH_MARKET_SALES.DIM_COUNTRY AS N2 ON E.CURRENT_NATIONKEY = N2.COUNTRY_ID;