----##### CHAPTER - 5 CREATING AND MODIFYING DATA ------
--MOSTLY DEALS WITH insert,update,delete AND merge.

--DATA TYPE:
--MAJOR DATA TYPES ARE CHARACTER,NUMERIC,TEMPORAL
--VARCHAR -> MAX SIZE 16MB -> STORES CHARACTER DATA USING UNICODE UTF-8 CHARACTER SET. EG: movie_name varchar(100) --> MAX LENGTH IS 100 BYTES... IF NOT SPECIFIED MAX LENGTH WILL BE ASSIGN I.E. 16MB. SIMILAR TO VARCHAR ARE CHAR,CHARACTER, CHAR VARYING, NVARCHAR, NVARCHAR2,NCHAR,NCHAR VARYING,STRING,TEXT THESE ARE USED BECAUSE PORTING FROM DIFFERENT DB IS EASY. MAJORITY COLOUMN WILL BE DEFINE AS VARCHAR.

--CHAR VERSUS VARCHAR: CHAR IS USED TO STORE FIXED LENGTH OF STRING WITH PAD. EX:CHAR(5) IT WILL HOLD 5 CHARACTER WITH RIGHT PADDED LIKE "CAT"--> "CAT  ". IN SNOWFLAKE CHAR IS OF VARIABLE LENGTH, IT WILL NEVER ADD SPACES TO THE END OF STRING. IN SNOWFLAKE CHAR LENGHT IS 1 BY DEFALULT.

SELECT 'HELLO WORLD' AS OUTPUT_STRING; --> CALLING SRING AS A COLUMN
SELECT 'SNOWFLAKE YOU HAVE''T REACH THE END YET' AS OUTPUT_STRING; --USE 2 APOSTROPHE FOR SINGLE QUOTE.
-- FOR COMPLEX STRING USE 2 DOLLAR SIGN ($$) AS DELIMITER, SNOWFLAKE WILL ACCEPT IT AS IT IS.
SELECT $$ STRING WITH 4 QUOTES ' ' ' ' $$ AS OPSTR;

--NUMERIC DATA: DATA TYPE number IN SNOWFLAKE CAN HANDLE ANY TYPE OF NUMERIC DATA, HOLDS UPTO 38 DIGITS EITHER WITH A DECIMAL POINT OR WITHOUT INTEGER.
--ANY OF THE FOLLOWING VALUE CAN BE ASSIGNED 0,1,-1,0.0000000000000..37 TIMES..0001 OR 1234567.123456789012345678901234567890 (TOTAL 38 DIGITS OR PRECISION). MAXIMUM NUMBER AFTER DECIMAL IS KNOWN AS scale. DEFAULT PRECISION AND SCALE IS number(38,0).
-- IF U WANT A RANGE OF -999.99 TO 999.99 THEN COLOUMN SHOULD BE number(3,2).
-- SNOWFLAKE ACCEPTS DECIMAL,NUMERIC,REAL,TINYINT,SMALLINT,INT,INTEGER,BIGINT,DOUBLE,FLOAT,FLOAT4,FLOAT8 FOR EASY PORTING OF DATA.
--STICK WITH integer FOR INTEGER & number FOR FLOATING NUMBERS

--TEMPORAL DATA: HOLDS DATA ABOUT DATE AND TIMES, LIKE BITHDAY (MM-DD-YYYY) OR START AND END OF WORK SHIFT, EXACT TIME WHICH REQUIRE DD-MM-YYYY HH:MM:SS.MS (LIKE VEHICLE PASSING TOLL-BOOTH) OR SENDING MEETING INVITE TO CALENDER OF DIFFERENT TIME ZONE.
--DATE RANGE: 1582-01-01 TO 9999-12-31
--TIME RANGE: 00:00:00 TO 23:59:59.9999999 ... PARTIAL SECONDS UPTO 9 DIGITS.
--TIMESTAMP: 1582-01-01 00:00:00 TO 9999-12-31 23:59:59.9999999

--FLAVORS OF TIMEZONE: 
--timestamp_ntz: NO SPECIFIC TIME ZONE
--timestamp_ltz: LOCAL TIME ZONE
--timestamp_tz: ALLOWS TIME ZONE TO BE SPECIFIC.

SHOW PARAMETERS LIKE 'timez%'; --> it will give timezone information of database.
alter session set timezone = 'America/New_York'; -- use alter session to change time zone of session.
select current_date(),current_time(),current_timestamp(),current_region(),current_account();

--SNOWFLAKE ALLOWED ALL OF THE FOLLOWING STRINGS LITERALS TO BE INSERTED: 24-OCT-2025 OR 2022-10-24 OR 10/24/2022.

SHOW PARAMETERS LIKE 'date_output%'; --> SINGLE DEFAULT FORMAT FOR DATE VALUES TO BE RETUNED.
ALTER SESSION SET date_output_format = 'YYYY-MM-DD';
-- THERE IS ALSO A timestamp_output_format PARAMETER WHICH DEFAULT TO 'YYYY-MM-DD HH24:MI:SS.FF3'.

--OTHER DATA TYPES: SPECIAL DATA TYPE, MAINLY USE FOR SEMISTRUCTUTRED DATA SUCH AS JSON DOCUMENT.

--BOOLEAN: KNOWN AS LOGICAL DATA TYPE. HOLD VALUE TRUE OR FALSE. IF REQUIRE BOOLEAN COLOUMN CAN BE NULL.
--FOR TRUE USE: 'TRUE','1','YES','T','Y','ON' (IF USING STRING VALUE).
--FOR FALSE USE: 'FALSE','0','NO,'F','N', 'OFF'  (IF USING INTEGER VALUE).
--0 IS FALSE AND ANY NONZERO IS TRUE (IF USING INTEGER VALUE).

--VARIANT: IT IS A SWISS ARMY KNIFE, IT CAN HOLD ANY TYPE OF DATA. PROVIDE A FLEXIBILITY WHEN STORING SEMISTRUCTURED DATA. INSERTING VALUE INTO A variant COLOUMN USE :: OPERATOR TO CAST A STRING,NUMBER,DATE,ETC.. WE CAN ALSO USE VARIEN TO STORE JSON DOCUMENTS.
SELECT 1::VARIANT,'ABC'::VARIANT,CURRENT_DATE::VARIANT;
-- USE BUILTIN FUNCTION typeof() TO GET DATATYPE BEING USED.
SELECT TYPEOF($$'HELLO WORLD IS A STRING/VARCHAR VALUE'$$::VARIANT); --VARCHAR
SELECT TYPEOF(FALSE::VARIANT); --BOOLEAN
SELECT TYPEOF (CURRENT_TIMESTAMP::VARIANT); --TIMESTAMP_LTZ

--ARRAY: DATA TYPE IS A VARIABLE LENGTH ARRAY OF variant VALUES. CREATE WITH INTIAL LENGTH OF 0 AND EXTEND LATER TO NO UPPER LIMIT ON ELEMENTS. OVERALL SIZE IS 16MB. SQUARE BRACKETS ([]) ARE USED AS DELIMITERS FOR ARRAY LITERALS.
SELECT [123,'ABC',CURRENT_DATE] AS MY_ARRAY; --[
--   123,
--   "ABC",
--   "2026-02-18"
-- ]
--ARRAY CAN BE FLATTENED INTO X ROWS (X=3 IN THIS CASE) BY USING A COMBINATION OF THE table() AND flatten() FUNCTION. BREAKING ALL ELEMENTS TO DIFFERENT ROWS SO THAT WE CAN USE SINGLE ELEMENTS WHEN NEED TO USE FROM THE LIST/ARRAY.
SELECT VALUE FROM TABLE(FLATTEN(INPUT=>  [123,'ABC',CURRENT_DATE] )); --123 /N "ABC" /N "2026-02-18" (/N : NEW LINE)

--OBJECT: STORES AN ARRY IN KEY-VALUE PAIRS. KEYS ARE VARCHAR AND VALUE IS VARIANT. FORMED USING {} AND SEPERATED USING COLONS.
SELECT {'NEW YEAR':'01/01','INDEPENDENCE DAY':'15/08','CHRISTMAS':'25/12'} AS MY_OBJECT;
--USE FLATTEN() AND TABLE() FUNCTION TO TRANSFORM RESULT INTO TABLE WITH TWO COLOUMS OF KEY AND VALUE.
SELECT KEY,VALUE FROM TABLE(FLATTEN({'NEW YEAR':'01/01','INDEPENDENCE DAY':'15/08','CHRISTMAS':'25/12'}));
--ALSO WE CAN USE DIFFERENT CONDITIONS TO RETRIVE DIFFERENT DATAS..
SELECT KEY,VALUE FROM TABLE(FLATTEN({'NEW YEAR':'01/01','INDEPENDENCE DAY':'15/08','CHRISTMAS':'25/12'})) WHERE KEY LIKE '%NEW%';

--CREATING TABLE:
CREATE TABLE PERSON (
FIRST_NAME VARCHAR(50),
CHILDERN ARRAY,
BIRTHDAY DATE,
YEAR_OF_EDUCATION NUMBER(2,0));

--POPULATING & MODIFYING TABLES
--INSETING ONE VALUE AT A TIME..
INSERT INTO PERSON (
    FIRST_NAME,
    CHILDERN,
    BIRTHDAY,
    YEAR_OF_EDUCATION
)
VALUES (
    'John',
    ARRAY_CONSTRUCT('Anna', 'Mike'),
    '1985-06-15',
    16
);
    
--INSERTING MULTIPLE VALUE AT A TIME...
    INSERT INTO PERSON (
    FIRST_NAME,
    CHILDERN,
    BIRTHDAY,
    YEAR_OF_EDUCATION
)
VALUES (
    'John',
    ARRAY_CONSTRUCT('Anna', 'Mike'),
    '1985-06-15',
    16
),
(
    'MARRY',
    NULL,
    '1988-06-15',
    15
);

--OVERWRITE: IT WILL REMOVE THE ROW AND RE-INSERT IT 
INSERT OVERWRITE INTO PERSON (
    FIRST_NAME,
    CHILDERN,
    BIRTHDAY,
    YEAR_OF_EDUCATION
)
VALUES (
    'John',
    ARRAY_CONSTRUCT('Anna', 'ROSE'),
    '1985-06-15',
    16
),
(
    'MARRY BROWN',
    NULL,
    '1988-06-15',
    15
);

--ALONG WITH USING values, YOU CAN USE A selecet STATEMENT TO GENERATE ONE OR MORE ROWS TO BE INSERTED. BASICALLY WE ARE ADDING NEW ROW USING EXISTING ROW.
INSERT INTO PERSON (FIRST_NAME,CHILDERN,BIRTHDAY,YEAR_OF_EDUCATION)
    SELECT 'MAX' AS FIRST_NAME, ['SAM'::VARIANT,'TOM'::VARIANT] AS CHILDERN,BITHDAY,20 AS YEAR_OF_EDUCATION FROM PERSON
    WHERE FIRST_NAME ILIKE 'MARRY BROWN'; 


--DELETING DATA: EXECUTE A delete STATEMENT USING A where CLAUSE TO SPECIFY ROWS TO BE REMOVED.
DELETE FROM PERSON_TABLE WHERE FIRST_NAME LIKE '%_B%';
--REMOVE ANY ROWS FROM PERSON WHERE A ROW EXISTS IN EMPLOYEE HAVING THE SAME NAME.
DELETE FROM PERSON_TABLE P USING EMPLOYEE_TABLE E WHERE E.EMP_NAME = CONCAT(P.FIRST_NAME,' ',P.LAST_NAME);


--TIME TRAVEL: ALLOWS YOU TO SEE THE STATE OF DATA AT A PARTICULAR POINT IN TIME. SNOWFLAKE STANDARD RETENTION PERIOD IS 24 HOURS WHERE AS FOR ENTERPRISE VERSION IT IS 90 DAYS.
--EX.: TRAVEL BACK 10 MINUTES FOR EMPLOYEE TABLE. I.E.600 MS
SELECT * FROM EMPLOYEE_TABLE AT (OFFSET => -600) WHERE EMP_NAME = 'GARE';

--NOW IF WANT TO INSERT SAME IN TABLE
INSERT INTO EMPLOYEE 
SELECT * FROM EMPLOYEE_TABLE AT (OFFSET => -600) WHERE EMP_NAME = 'GARE';

--MODIFYING DATA: USE update TO MODIFY THE EXISTING DATA. USE where CLAUSE TO IDENTIFY THE ROWS THEN USE set CLAUSE TO DESCRIBE THE CHANGES
UPDATE STG_EG.STG_EG_SALES_NATIONAL_MTH 
SET CHANNEL = 'HOSPITAL'  -- SINGLE CHANGE
WHERE (CHANNEL = 'NON RETAIL'  OR CHANNEL = 'NONRETAIL') AND (CHANNEL IS NOT NULL);

UPDATE STG_EG.STG_EG_SALES_NATIONAL_MTH 
SET CHANNEL = 'HOSPITAL', MANUFACTURER = NULL --MULTIPLE CHANGE AT ONCE.
WHERE (CHANNEL = 'NON RETAIL'  OR CHANNEL = 'NONRETAIL') AND (CHANNEL IS NOT NULL);

UPDATE STG_EG.STG_EG_SALES_NATIONAL_MTH AS E
SET LC_1 = SUM(E.LC_1) - 1000 -- SETTING VALUE BASE ON DIFFERENT TABLE.
FROM DF_CHC_MARKET_PROD.DWH_MARKET_SALES.DIM_COUNTRY AS D
WHERE UPPER(D.COUNTRY) = 'EGYPT';

-- BLOCKING UPDATE ON MULTIPLE JOIN; I.E. UPDATEING STATEMENT ON BASIS OF DIFFERENT TABLE WILL BE BLOCKED.
ALTER SESSION SET ERROR_ON_NONDETERMINISTIC_UPDATE = TRUE;

--MERGING DATA: EXECUTING A SINGLE MERGE STATEMENT TO ADD ANY NEW ROW, REMOVE ROWS NO LONGER NEEDED AND MODIFYING ANY EXISTING ROWS. IT WILL CHANGE THE ROW WITHOUT EFFECTIING OTHER ROWS.
MERGE INTO STG_EG.STG_EG_SALES_NATIONAL_MTH AS E
USING DWH_MARKET_SALES.DIM_COUNTRY AS DC 
ON UPPER(DC.COUNTRY) = E.COUNTRY AND E.MANUFACTURER = NULL
WHEN MATCHED AND E.CORPORARION IS NULL THEN DELETE
WHEN MATCHED THEN UPDATE SET E.MANUFACTURER = '0', E.LC_1 = '0', E.LC_60 = '0'
WHEN NOT MATCHED THEN INSERT (CORPORATION,MANUFACTURER) VALUES (DC.CORPORATION, DC.MANUFACTURER);