-------##### CHAPTER - 6 DATA GENERATION, CONVERSION AND MANIPULATION ------

--STRING GENERATION AND MANIPULATION
SELECT 'HERE IS MY STRING'; -- A STRING IS A SIMPLE MATTER OF ENCLOSING UR STRING IN SINGLE QUOTES.
SELECT 'STRING 1' || 'AND' || 'STRING 2'; -- CONCATENATE STRING USING ||.
SELECT CONCAT('STRING 1','AND','STRING 2'); -- CONCATENATING USING BUILTIN FUNCTION concat().

-- IF ANT SYMBOL IS NOT PRESENT ON KEYBOARD THEN USE ASCII VALUE IN char() FUNCTION 
SELECT CONCAT('I SPENT ',CHAR(8364),' 123 IN PARIS. '); --O/P:I SPENT € 123 IN PARIS. 

--CHANGING CASE OF A STRING.
SELECT UPPER(STR.VAL), --I VISIT PARIS; ALL IN CAPITAL LETTERS
LOWER(STR.VAL), --i visit paris; ALL IN SMALL LETTERS
INITCAP(STR.VAL) -- I Visit Paris ; ALL IN TITLE CASE.
FROM VALUES('I VISIT PARIS') AS STR(VAL);

--REVERSING THE STRING
SELECT REVERSE('?SIHT DAER UOY NAC'); -- O/P: REVERSING THE STRING: CAN YOU READ THIS?

--USING TRIM FOR REMOVING THE EMPTY SPACES
SELECT LTRIM(STR.VAL), --REMOVE LEFT SPACE
RTRIM(STR.VAL), --REMOVE RIGHT SPACE
TRIM(STR.VAL) --REMOVE BOTH SIDE SPACE
FROM VALUES('  ABC  ') AS STR(VAL);

--LENGHT FUNCTION: RETURN LENGHT OF A STRING.
SELECT LENGTH(LTRIM(STR.VAL)), --REMOVE LEFT SPACE LENGTH IS 5
LENGTH(RTRIM(STR.VAL)), --REMOVE RIGHT SPACE LENGTH IS 5
LENGTH(TRIM(STR.VAL)) --REMOVE BOTH SIDE SPACE LENGTH IS 3
FROM VALUES('  ABC  ') AS STR(VAL);

--REPLACE OF A CHARACTER. USE translate TO CONVERT OR replace ANY CHARATER IN STRING.
SELECT TRANSLATE('(+91) 123456789', '()-',''); -- FROM (+91) 123456789 REPLACE '()-' <-- THESE CHARACTERS TO '', O/P: +91 123456789
SELECT TRANSLATE('AxByCz','ABC','XYZ'); --REPLACE A SET OF CHARACTER WITH DIFFERENT SET. : XxYyZz

--STRING SEARCHING AND EXTRACTING: 
--position() FUNCTION: FIND POSITION OF A STRING WITHIN A STRING, ELSE 0 IF THE SUBSTRING IS'NT FOUND. ALSO ALLOWS TO SPECIFY THE STARTING POSITION.

SELECT POSITION('HERE',STR.VAL) AS POS1, --O/P: 1
POSITION('HERE',STR.VAL,10) AS POS2, -- SEARCHING BEGINS FROM 10TH INDEX O/P: 23
POSITION('NOWHERE',STR.VAL) AS POS3 -- O/P: 0
FROM VALUES('HERE THERE, AND EVERYWHERE') AS STR(VAL);

--SUBSTR(): SHOWS PART OF STRING FROM SPECIFIED POSITION AND STARTING POSITION AS AN OPTIONAL NUMBER OF CHARACTER
SELECT SUBSTR(STR.VAL, 2,10) AS STARTING_OF_STRING,  --BEGINNING (FETCHING STARTS FROM 2 AND ENDS ON 10)
SUBSTR(STR.VAL,12) AS REST_OF_STRING  --ENDING' (FETCHING ENDS ON 12)
FROM VALUES($$'BEGINNING ENDING'$$) AS STR(VAL);

--startswith(): A BOOLEN TYPE FUNCTION,WHICH RETURN STRING IF STRING STARTS WITH SPECIFIED CHARACTER ELSE NO OUTPUT
SELECT STR.VAL 
FROM VALUES ('HERE, THERE AND EVERYWHERE') AS STR(VAL)
WHERE STARTSWITH(STR.VAL,'WHERE');  -- NO RESULT

SELECT STR.VAL 
FROM VALUES ('HERE, THERE AND EVERYWHERE') AS STR(VAL)
WHERE STARTSWITH(STR.VAL,'HERE');  --HERE, THERE AND EVERYWHERE

--endswith(): A BOOLEN TYPE FUNCTION,WHICH RETURN STRING IF STRING ENDS WITH SPECIFIED CHARACTER ELSE NO OUTPUT
SELECT STR.VAL 
FROM VALUES ('HERE, THERE AND EVERYWHERE') AS STR(VAL)
WHERE ENDSWITH(STR.VAL,'HERE'); --'HERE, THERE AND EVERYWHERE'

--contains():  A BOOLEN TYPE FUNCTION,WHICH RETURN STRING IF STRING IS PRESENT WITH SPECIFIED CHARACTER ELSE NO OUTPUT
SELECT STR.VAL 
FROM VALUES ('HERE, THERE AND EVERYWHERE') AS STR(VAL)
WHERE CONTAINS(STR.VAL,'AND'); --'HERE, THERE AND EVERYWHERE'

--- WORKING WITH NUMERIC DATA: 
--USING OF ARITHMATIC OPERATORS +,-,*,/  TO PERFORM CALCULATIONS

SELECT 10 AS RADIUS, 2*3.14159*10 AS CIRCUMFERENCE;
SELECT (3*6) - (10/2); -- USE PARANTHESIS IN ORDER TO DICTATE CALCULATION PRECEDENCE O/P: 13.000000

--NUMERICAL FUNCTION:
SELECT 10 AS RADIUS, PI() * POWER(10,2) AS AREA; -- PIE*10^2; USING PIE VALUE AND POWER FUNCTION O/P: 314.1592
SELECT MOD(10,3); -- USE mod() FUNCTION TO FIND REMAINDER AFTER 10/3 O/P:1

SELECT SIGN(-7.009),  -- SIGN FUNCTION PROVIDES THE SIGN OF NUMBER AS -1 FOR -VE, +1 FOR +VE AND 0 FOR 0. O/P: -1
ABS(-7.45); --RETURNS ABSOLUTE VALUE O/P: 7.45 (REGARLESS OF ANY SIGN.)

SELECT TRUNC(6.49), --WHILE DEALING WITH REAL NUMBERS IS HELPS TO GET GREATES INTEGER FUNCTION (GIF) (BEFORE DECIMAL) O/P: 6
ROUND(6.49,1), --IT ROUNDSOFF THE VALUE (HERE IT IS ROUNDING OFF TO 0.01 TERMS) O/P: 6.5
FLOOR(6.49), -- IT ROUND OFFS TO GIF TO LOWER VALUE O/P: 6
CEIL(6.49); -- IT ROUND OFFS TO GIF TO UPPER VALUE O/P: 7

---NUMERIC CONVERSION:TO CONVERT A STRING TO A NUMBER, THERE ARE SEVERAL STRATEGIES: EXPLICIT CONVERSION, WHERE YOU SPECIFY THAT THE STRING BE CONVERTED TO A NUMBER, AND IMPLICIT CONVERSION (ALSO KNOWN AS COERCION), WHERE SNOWFLAKE SEES THE NEED FOR THE CONVERSION AND ATTEMPTHS TO DO SO.

SELECT 123.45 AS REAL_NUM
UNION
SELECT '678.90' AS REAL_NUM; -- IMPLICIT CONVERSION (ALSO KNOWN AS COERCION)

SELECT 123.45 AS REAL_NUM 
UNION
SELECT 'AAA.BB' AS REAL_NUM; --Numeric value 'AAA.BB' is not recognized.

--EXPLICITLY REQUEST A DATA CONVERSION USING ONE OF THE FOLLOWING LIKE cast() FUNCTION, cast operator ::, SPECIFIC CONVERSION FUNCTION SUCH AS to_decimal().

SELECT CAST(STR.VAL AS NUMBER(7,2)) AS CAST_VAL,
STR.VAL::NUMBER(7,2) AS CAST_OPERATOR_VAL,
TO_DECIMAL(STR.VAL,7,2) AS TO_DEC_VAL,
TO_DECIMAL(STR.VAL1, '$999.99',7,2) AS CHARACTER_IMBEDMENT, -- ADDING A NONNUMERIC CHARACTER IN FRONT OF VALUE
TRY_TO_DECIMAL(STR.VAL1,'$9999.99',7,2) AS GOOD, -- TRY_TO_DECIMAL WILL TEST CONVERSION AND RETURNS NULL IF CONVERSION FAIL INSTEAD OF ERROR.
TRY_TO_DECIMAL(STR.VAL1,'999.99',7,2) AS BAD -- HERE WE ARE KEEPING LESS DIGITS AND NOT PROVIDING $ SYMBOL.
FROM VALUES ('157.78','$157.78') AS STR(VAL,VAL1); --(IF HERE, THERE IS ANY NON-NUMERIC VALUE IN STR.VAL THE CONVERSION WILL FAIL, TO USE OR DEFINE ANY NON-NUMERIC CHARACER USE STR.VAL1 STYLE).

--NUMERIC GENERATION: 
--generator() FUNCTION IS A table function USED TO GENERATE ROWS OF DATA. TABLE FUNCTION ARE CALLED IN THE FROM CLAUSE OF A QUERY.

SELECT RANDOM() FROM TABLE (GENERATOR(ROWCOUNT => 10 ));-- WILL GENERATE 10 RANDOM NUMBERS.
SELECT SEQ1() FROM TABLE(GENERATOR(ROWCOUNT => 6)); --IT WILL GENERATE 6 SEQUENTIAL NUMBER FROM 0 TO 5.

SELECT TO_DATE('01/'|| TO_CHAR(SEQ1()+1) || '/2026', 'DD/MM/YYYY') AS FIRST_OF_MONTH FROM TABLE(GENERATOR(ROWCOUNT => 12)); --GENERATING FIRST DATE OF MONTH USING GENERATOR SEQ1, HERE GENERATOR WILL GENERATE NUMBER FROM 0 TO 11 SO WE ADD 1 IN SEQ1

SELECT DAYNAME(TO_DATE('01/'|| TO_CHAR(SEQ1()+1) || '/2026', 'DD/MM/YYYY')) AS FIRST_OF_MONTH FROM TABLE(GENERATOR(ROWCOUNT => 12)); --GENERATING DAY NAME OF FIRST DATE OF MONTH USING GENERATOR SEQ1.

--WORKING WITH TEMPORAL DATA: 
--MOST COMPLEX OF ALL DATA TYPE CAUSE THERE ARE MANY WAYS IN WHICH DATE CAN BE DESCRIBE.  
--LIKE 11/03/2022 OR THRUSDAY, NOVEMBER 2,2022 OR 2022-11-03 15:48:49.44 -0700 OR 03-NOV-2022 06:48:56 PM EST.

SELECT TO_TIMESTAMP('04-NOV-2022 18:48:56', 'DD-MON-YYYY HH24:MI:SS') AS NOW; --CONVERTING TIME TO 'DD-MON-YYYY HH24:MI:SS'
SHOW PARAMETERS LIKE 'TIMESTAMP_OUT%'; -- SHOWS ALL THE INFO RELATED TO TIME.
ALTER SESSION SET TIMESTAMP_OUTPUT_FORMAT = 'MM/DD/YYYY HH12:MI:SS AM TZH'; --> IT WILL CHANGE THE TIME FORMAT OUTPUT STYLE.

--DATE AND TIME STAMP GENERATION
-- HERE YOU CAN PASS A STRING AND SNOWFLAKE WILL FIGURE OUT TO CONVERT USING IMPLICIT CONVERSION.
--DATE_FROM_PARTS ALLOWS TO CONVERT DATE FROM USING SIMPLE NUMERICALS.IT ALSO ALLOWS TO MOVEBACK IN TIME USING 0 AND -VE NUMBERS. 0 WILL MOVE BACK BY ONE DAY SIMILARLY -1 WILL BE MOVEMENT OF 2 DAYS BACKWARD. HANDY FOR FINDING MONTHS END DATES WITHOUT HAVING TO REMEMBER WHICH MONTH HAVE 30 OR 31 DAY.

SELECT DATE_FROM_PARTS(2023,3,14) AS MY_DATE,
TIME_FROM_PARTS(10,55,59) AS MY_TIME,
TIMESTAMP_FROM_PARTS(DATE_FROM_PARTS(2023,3,14), TIME_FROM_PARTS(10,55,59)) AS MY_FULL_DATE;

SELECT DATE_FROM_PARTS(2025,SEQ1 ()+2 ,0) AS MONTH_END FROM TABLE(GENERATOR(ROWCOUNT => 12));

--MANIPULATIG DATES AND TIMESTAMPS
--TEMPORAL FUNCTIONS THAT RETURN DATES: 
--date_trunc(): RETRIEVE A DATE FROM COLOUMN AND DETERMNINE BEGNING OF MONTH, QUARTER,YEAR ASSOCIATED WITH THAT DATE.

SELECT DATE_TRUNC('YEAR',DT.VAL) AS START_OF_YEAR, --2026-01-01
DATE_TRUNC('MONTH',DT.VAL) AS START_OF_MONTH, --2026-05-01
DATE_TRUNC('QUARTER',DT.VAL) AS START_OF_QUARTER, --2026-04-01
FROM VALUES(TO_DATE('26-MAY-2026','DD-MON-YYYY')) AS DT(VAL);

--dateadd(): ALLOWS ONE OR MORE INCRIMENTS OF A GIVEN UNIT OF TIME (SUCH AS DAY, MONTH,YEAR, HOUR OR MINUTE) TO BE ADDED.
SELECT 
DATEADD(MONTH,1, TO_DATE('01-JAN-2024','DD-MON-YYYY')) AS DATE1, --2024-02-01
DATEADD(MONTH,1, TO_DATE('31-DEC-2024','DD-MON-YYYY')) AS DATE2, --2025-01-31
DATEADD(YEAR,-1,TO_DATE('29-FEB-2024','DD-MON-YYYY')) AS NEW_DATE, --2023-02-28
DATEADD(DAY,-1,TO_DATE('01-MAR-2024','DD-MON-YYYY')) AS NEW_DATE2; --2024-02-29

--dayname() AND monthname() : EXTRACT DAY AND MONTH NAME RESPECTIVELY FROM THE DATE.
SELECT DAYNAME(CURRENT_DATE), MONTHNAME(CURRENT_DATE); --Sat , Feb

-- FUNCTIONS RETURNING INTEGER VALUE FOR DATES
--date_part() USE TO EXTRACT VARIOUS UNIT OF DATE AND TIME IN INTEGER FORMAT.
SELECT DATE_PART(YEAR,DT.VAL) AS YEAR, --2025
DATE_PART(QUARTER,DT.VAL) AS QUARTER, --3
DATE_PART(MONTH,DT.VAL) AS MONTH, --7
DATE_PART(WEEK,DT.VAL) AS WEEK, --30
DATE_PART(HOUR,DT.VAL1) AS HOUR, --7
DATE_PART(MINUTE,DT.VAL1) AS MINUTE, --24
DATE_PART(SECOND,DT.VAL1) AS SECOND, --23
DATE_PART(NANOSECOND,DT.VAL1) AS NANOSECOND --209000000
FROM VALUES(TO_DATE('2025-07-23','yyyy-mm-dd'),CURRENT_TIMESTAMP()) AS DT(VAL,VAL1);

--datediff(): FUNCTION RETURN DIFFERENCE BETWEEN 2 DATES. REGARDLESS OF BIGGERDATE - SMALLERDATE OR VISE-VERSA, YOU CAN WRAP CELL IN abs() TO GET DIRECT VALUE RATHER THAN -VE SIGN.

SELECT DATEDIFF(YEAR,DT.VAL1 ,DT.VAL2) NUM_YEAR, --27
DATEDIFF(MONTH,DT.VAL1 ,DT.VAL2) NUM_MONTH, --324
DATEDIFF(DAY,DT.VAL1 ,DT.VAL2) NUM_DAY, --9878
DATEDIFF(HOUR,DT.VAL1 ,DT.VAL2) HOUR, --237072
FROM VALUES(TO_DATE('12-FEB-1999','DD-MON-YYYY'), CURRENT_DATE()) AS DT(VAL1,VAL2);

--DATE CONVERSION: 
--USE to_date() FUNCTION TO CONVERT STRING TO DATE, THIS CAN ALSO BE DONE BY USING cast().
SELECT CAST('23-SEP-2023' AS DATE) AS FORMAT1, --2023-09-23
CAST('09/23/2024' AS DATE) AS FORMAT2,  --2023-09-23
CAST('2023-09-23' AS DATE) AS FORMAT3;  --2023-09-23
--ABOVE FORMAT DATE CAN BE EASILY RESOLVED BY SNOWFLAKE.SOMETIME IT CAN MAKE MISTAKE, SO USE TRY_CAST() TO AVOID ERROR, AND GET RESULT OR NULL.

SELECT CAST('09-23-2024' AS DATE); --Date '09-23-2024' is not recognized
SELECT TRY_CAST('09-23-2024' AS DATE); --NULL

SELECT CAST('123.45' AS NUMBER(6,3)), --123.450
CAST(123.456 AS INTEGER); -- 123

-- WE CAN ALSO USE :: OPERATOR INSTEAD OF CAST() ONLY DOWNSIDE OF :: IS THERE IS NO 'try' LIKE try_cast().
SELECT '09/23/2023':: DATE DATE_VAL, --2023-09-23
'23-SEP-2023':: TIMESTAMP TMP_VAL, --2023-09-23 00:00:00.000
'123.456'::NUMBER(6,3) NUM_VAL; --123.456

--TRY TO SPLIT A DECIMAL NUMBER TO 2 DIFFERENT COLOUMN 
SELECT CAST('123.456' AS INTEGER) AS GIF, --123
TRANSLATE(123.456 - CAST('123.456' AS INTEGER),'.','') AS SIF;-- 0456

SELECT 
ABS(CAST(LC AS INTEGER)) AS GIF,
ABS(TRANSLATE(LC - CAST(LC AS INTEGER),'.','')) AS SIF 
FROM
(SELECT LC FROM PSA_AU.PSA_AU_DIST_MTH_TRANSP WHERE LC > 0) AS X;