----##### CHAPTER - 4 SETS ------
--INTRACT WITH YOUR DATA ONE ROW AT A TIME, RELATIONAL DATABASE ARE RELLY ALL ABOUT SETS,THE USE OF sets operators, WHICH ALLOWS YOU TO COMBINE DATA FROM MULTIPLE RESULT SETS.
--SET OPRATORS ARE UNION,INTERSECT AND EXCEPT <-- USING THIS WE CAN COMBINE MULTIPLE DATA.
-- THESE POWERFUL TOOLS ARE USED TO PERFORM DATA ANALYSIS AND CRAFTING REPORTS.

--SET THEORY PRIMER
-- A = {1,2,4,7,9}; B = {3,5,7,9} --> A UNION B {1,2,3,4,5,7,9} -- ALL ELEMENT ARE SORTED AND UNIQUE ELEMENTS FROM BOTH THE SETS.
-- A = {1,2,4,7,9}; B = {3,5,7,9} --> B UNION A {1,2,3,4,5,7,9}
-- A = {1,2,4,7,9}; B = {3,5,7,9} --> A INTERSET B {7,9}
--A = {1,2,4,7,9}; B = {3,5,7,9} --> B INTERSET A {7,9}
-- A = {1,2,4,7,9}; B = {3,5,7,9} --> A EXCEPT B {1,2,4} (EXCEPT MAY ALSO USE AS minus UNTERCHANGEABLY)
-- A = {1,2,4,7,9}; B = {3,5,7,9} --> B EXCEPT A {3,5} -- OUT OF THREE SET OPERATION except IS ONLY ONE THAT YIELDS A DIFFERENT RESULT IF YOU SWITCH THE ORDER OF THE SET.
-- MYSTERY OPERATION: ADVANCE USING OF BASIC SET OPRATION : (A UNION B) EXCEPT (A INTERSECTION B) OR (A EXCEPT B) UNION (B EXCEPT A)

--THE UNION OPERATOR: ALLOWS YOU TO COMBINE TWO OR MORE DATA SETS..
SELECT 1 AS NUMERIC_COL , 'ABC' AS STING_COL 
UNION
SELECT 5 AS NUMERIC_COL , 'XYZ' AS STING_COL; -- HERE, IT IS ABOUT SIMPLE AS IT GETS: TWO SINGLE-ROW RESULT SETS, WITHOUT ANY OVERLAPPING VALUES, COMBINING TO MAKE A TWO-ROW RESULT SET. THIS TYPE OF STATEMENT IS KNOWN AS A compound query BECAUSE IT CONTAIN TWO INDEPENDENT QUERIES SEPERATED BY A SET OPERATOR.
-- RESTRICTIONS RELATED TO THE TWO SET BEING COMBINED: BOTH SETS MUST OF SAME COLOUMN AND DATA TYPE SHOULD BE MATCHING RESPECTIVELY.
SELECT 1 AS NUMERIC_COL , 'ABC' AS STING_COL 
UNION
SELECT 5 AS NUMERIC_COL , 'XYZ' AS STING_COL,99 AS EXTRA_COL; -- SQL compilation error: invalid number of result columns for set operator input branches, expected 2, got 3 in branch 2
SELECT 1 AS NUMERIC_COL , 'ABC' AS STING_COL 
UNION
SELECT 'XYZ' AS NUMERIC_COL , 5 AS STING_COL; --Numeric value 'ABC' is not recognized.

SELECT INTEGER_VAL FROM (VALUES (1),(2),(4),(7),(9)) AS SET_A (INTEGER_VAL) -- USING VALUE SUBCLAUSE TO GENERATE ON THE GO DATA.
UNION
SELECT INTEGER_VAL FROM (VALUES (3),(5),(7),(9)) AS SET_B (INTEGER_VAL); --UNION COMBINES BOTH RESULT AND REMOVE DUPLICATES.

SELECT INTEGER_VAL FROM (VALUES (1),(2),(4),(7),(9)) AS SET_A (INTEGER_VAL)
UNION ALL
SELECT INTEGER_VAL FROM (VALUES (3),(5),(7),(9)) AS SET_B (INTEGER_VAL); --UNION ALL COMBINES BOTH RESULT AND DON'T REMOVE DUPLICATES.

SELECT * FROM STG_EG.STG_EG_SALES_NATIONAL_MTH  WHERE CHANNEL = 'NON RETAIL' AND LC_60 > 100
UNION
SELECT * FROM STG_EG.STG_EG_SALES_NATIONAL_MTH  WHERE CHANNEL = 'RETAIL' AND LC_1 IS NOT NULL;

SELECT  * FROM STG_EG.STG_EG_SALES_NATIONAL_MTH 
WHERE (CHANNEL = 'NON RETAIL' AND LC_60 > 100) OR (CHANNEL = 'RETAIL' AND LC_1 IS NOT NULL); -- REPLICATING ABOVE QUERY WITHOUT USING where CLAUSE.

--THE INTERSECT OPERATOR: IT IS USED TO FIND THE INTERSECTION BETWEEN TWO DATA SETS.
SELECT INTEGER_VAL FROM (VALUES (1),(2),(4),(7),(9)) AS SET_A (INTEGER_VAL)
INTERSECT
SELECT INTEGER_VAL FROM (VALUES (3),(5),(7),(9)) AS SET_B (INTEGER_VAL); -- ONLY TAKING COMMON VALUE FROM BOTH SETS.

--THE EXCEPT OPERATOR: SET OPERATOR IS USED TO RETURN ROWS FROM SET A WITHOUT ANY OVERLAP WITH SET B
SELECT INTEGER_VAL FROM (VALUES (1),(2),(4),(7),(9)) AS SET_A (INTEGER_VAL)
EXCEPT
SELECT INTEGER_VAL FROM (VALUES (3),(5),(7),(9)) AS SET_B (INTEGER_VAL); -- TAKING ALL VALUES FROM SET A AND REMOVING SET B VALUES FROM SET A

SELECT INTEGER_VAL FROM (VALUES (3),(5),(7),(9)) AS SET_B (INTEGER_VAL)
EXCEPT
SELECT INTEGER_VAL FROM (VALUES (1),(2),(4),(7),(9)) AS SET_A (INTEGER_VAL); -- TAKING ALL VALUES FROM SET B AND REMOVING SET A VALUES FROM SET B

--- SET OPERATION RULES: THERE MAY BE ONLY BE ONE order by CLAUSE, AND IT MUST BE AT THE END OF THE STATEMENT AND WHEN SPECIFYING COLUMN NAME IN THE order by CLAUSE, YOU MUST USE THE COLUMN NAME/ALIASES FROM THE FRIST QUERY.
SELECT DISTINCT(S1.MOLECULE) AS distinct_s1_molecule ,LENGTH(S1.MOLECULE) AS S1_LEN FROM STG_EG.STG_EG_SALES_NATIONAL_MTH AS S1 WHERE CHANNEL = 'NON RETAIL' AND LC_60 > 100
UNION
SELECT DISTINCT(S2.MOLECULE) AS distinct_s2_molecule, LENGTH(S2.MOLECULE) AS S2_LEN FROM STG_EG.STG_EG_SALES_NATIONAL_MTH AS S2 WHERE CHANNEL = 'RETAIL' AND LC_1 IS NOT NULL
ORDER BY S1_LEN;

SELECT DISTINCT(S1.MOLECULE) AS distinct_s1_molecule ,LENGTH(S1.MOLECULE) AS S1_LEN FROM STG_EG.STG_EG_SALES_NATIONAL_MTH AS S1 WHERE CHANNEL = 'NON RETAIL' AND LC_60 > 100
UNION
SELECT DISTINCT(S2.MOLECULE) AS distinct_s2_molecule, LENGTH(S2.MOLECULE) AS S2_LEN FROM STG_EG.STG_EG_SALES_NATIONAL_MTH AS S2 WHERE CHANNEL = 'RETAIL' AND LC_1 IS NOT NULL
ORDER BY S2_LEN; --> SQL compilation error: error line 540 at position 9 invalid identifier 'S2_LEN'

--SET OPERATION PRECEDENCE: MYSTERY OPERATION: ADVANCE USING OF BASIC SET OPRATION : (A UNION B) EXCEPT (A INTERSECTION B) OR (A EXCEPT B) UNION (B EXCEPT A)
-- USE PARENTHESES FOR CORRECT RESULTS
SELECT INTEGER_VAL FROM (VALUES (1),(2),(4),(7),(9)) AS SET_A (INTEGER_VAL)
EXCEPT
SELECT INTEGER_VAL FROM (VALUES (3),(5),(7),(9)) AS SET_B (INTEGER_VAL)

UNION 

SELECT INTEGER_VAL FROM (VALUES (3),(5),(7),(9)) AS SET_B (INTEGER_VAL)
EXCEPT
SELECT INTEGER_VAL FROM (VALUES (1),(2),(4),(7),(9)) AS SET_A (INTEGER_VAL);--> O/P 5,3

-- USE PARENTHESES FOR CORRECT RESULTS
(SELECT INTEGER_VAL FROM (VALUES (1),(2),(4),(7),(9)) AS SET_A (INTEGER_VAL)
EXCEPT
SELECT INTEGER_VAL FROM (VALUES (3),(5),(7),(9)) AS SET_B (INTEGER_VAL))
UNION 
(SELECT INTEGER_VAL FROM (VALUES (3),(5),(7),(9)) AS SET_B (INTEGER_VAL)
EXCEPT
SELECT INTEGER_VAL FROM (VALUES (1),(2),(4),(7),(9)) AS SET_A (INTEGER_VAL)); --> O/P: 2,1,4,5,3